'use client';
import { useEffect, useState } from 'react';
import AppLayout from '@/components/AppLayout';
import { stockSuggestionsAPI } from '@/lib/api';
import { Sparkles, TrendingUp, ShieldCheck, AlertCircle } from 'lucide-react';

export default function StockSuggestionsPage() {
  const [suggestions, setSuggestions] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    stockSuggestionsAPI.getAll()
      .then((res) => {
        setSuggestions(res.data);
        setLoading(false);
      })
      .catch((err) => {
        console.error("Failed to load stock suggestions", err);
        setLoading(false);
      });
  }, []);

  const getRiskBadge = (risk: string) => {
    switch(risk) {
      case 'Low': return 'bg-emerald-50 text-emerald-600 border-emerald-200';
      case 'Medium': return 'bg-amber-50 text-amber-600 border-amber-200';
      case 'High': return 'bg-orange-50 text-orange-600 border-orange-200';
      case 'Very High': return 'bg-red-50 text-red-600 border-red-200';
      default: return 'bg-slate-50 text-slate-600 border-slate-200';
    }
  };

  if (loading) return (
    <AppLayout>
      <div className="flex items-center justify-center py-20">
        <div className="w-6 h-6 border-2 border-blue-600/20 border-t-blue-600 rounded-full animate-spin" />
      </div>
    </AppLayout>
  );

  return (
    <AppLayout>
      <div className="space-y-6">
        
        {/* Header */}
        <div className="border-b border-slate-200 pb-4">
          <h1 className="text-xl font-bold text-slate-800 flex items-center gap-2">
            <Sparkles className="text-blue-600" size={24} />
            AI Stock Ideas for Future Profits
          </h1>
          <p className="text-xs text-slate-500 mt-1">High-conviction stock suggestions generated by Loki AI based on technicals and fundamentals.</p>
        </div>

        {/* Suggestion Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {suggestions.map((stock) => (
            <div key={stock.id} className="section-card flex flex-col h-full hover:shadow-lg transition-shadow border border-slate-200 bg-white">
              {/* Card Header */}
              <div className="p-4 border-b border-slate-100 flex justify-between items-start">
                <div>
                  <h3 className="font-bold text-slate-800 text-lg">{stock.symbol}</h3>
                  <p className="text-xs font-semibold text-slate-500">{stock.company_name}</p>
                </div>
                <div className="text-right">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-blue-600 bg-blue-50 px-2 py-1 rounded">
                    {stock.category}
                  </span>
                </div>
              </div>

              {/* Price Data */}
              <div className="p-4 grid grid-cols-2 gap-4 bg-slate-50/50">
                <div>
                  <p className="text-[10px] text-slate-400 font-bold uppercase">Current Price</p>
                  <p className="font-mono font-semibold text-slate-800">₹{stock.current_price.toLocaleString()}</p>
                </div>
                <div>
                  <p className="text-[10px] text-slate-400 font-bold uppercase">AI Target</p>
                  <p className="font-mono font-bold text-emerald-600 flex items-center gap-1">
                    ₹{stock.target_price.toLocaleString()}
                    <TrendingUp size={12} />
                  </p>
                </div>
                <div>
                  <p className="text-[10px] text-slate-400 font-bold uppercase">Expected Upside</p>
                  <p className="font-semibold text-emerald-600">+{stock.potential_upside}%</p>
                </div>
                <div>
                  <p className="text-[10px] text-slate-400 font-bold uppercase">Time Horizon</p>
                  <p className="font-semibold text-slate-700">{stock.time_horizon}</p>
                </div>
              </div>

              {/* Rationale */}
              <div className="p-4 flex-grow">
                <p className="text-xs text-slate-600 leading-relaxed font-normal">
                  <strong className="text-slate-800">Why Buy?</strong> {stock.rationale}
                </p>
              </div>

              {/* Footer */}
              <div className="p-4 border-t border-slate-100 flex justify-between items-center bg-slate-50/50 rounded-b-xl">
                <div className="flex items-center gap-1.5">
                  <ShieldCheck size={14} className="text-blue-500" />
                  <span className="text-[10px] font-bold text-slate-600">AI Confidence: {stock.ai_confidence_score}%</span>
                </div>
                <span className={`text-[10px] font-bold px-2 py-0.5 rounded border uppercase ${getRiskBadge(stock.risk_level)}`}>
                  {stock.risk_level} Risk
                </span>
              </div>
            </div>
          ))}
        </div>

        {/* Disclaimer */}
        <div className="p-4 rounded border border-amber-200 bg-amber-50 flex items-start gap-2.5">
          <AlertCircle size={16} className="text-amber-600 mt-0.5 flex-shrink-0" />
          <p className="text-xs text-amber-800 leading-normal font-normal">
            <strong>Not SEBI Registered Advice:</strong> These stocks are generated by AI analysis for educational and idea-generation purposes only. Always conduct your own research or consult a financial advisor before investing.
          </p>
        </div>

      </div>
    </AppLayout>
  );
}
